from __future__ import annotations

from enum import StrEnum


class AccountState(StrEnum):
    NEW = "NEW"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    READY = "READY"
    BUSY = "BUSY"
    COOLDOWN = "COOLDOWN"
    RESTRICTED = "RESTRICTED"
    INVALID_SESSION = "INVALID_SESSION"
    DISABLED = "DISABLED"


class SourceState(StrEnum):
    NEW = "NEW"
    RESOLVING = "RESOLVING"
    READY = "READY"
    SCANNING = "SCANNING"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class JobState(StrEnum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSING = "PAUSING"
    PAUSED = "PAUSED"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    COMPLETING = "COMPLETING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class JobMemberState(StrEnum):
    CANDIDATE = "CANDIDATE"
    READY = "READY"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    SKIPPED = "SKIPPED"
    RETRY_WAIT = "RETRY_WAIT"
    FINAL_FAIL = "FINAL_FAIL"


class ErrorScope(StrEnum):
    MEMBER = "MEMBER"
    ACCOUNT = "ACCOUNT"
    TARGET = "TARGET"
    NETWORK = "NETWORK"
    SYSTEM = "SYSTEM"
